export const MODULE_NAME = "JENNY_MODULE";

export const actionTypes = {
  CHECK_NUM: `${MODULE_NAME}/CHECK_NUM`,
  CHECK_NUM_SUCCESS: `${MODULE_NAME}/CHECK_NUM_SUCCESS`,
  CHECK_NUM_FAILURE: `${MODULE_NAME}/CHECK_NUM_FAILURE`,
};
